# Generated by Django 5.0.2 on 2024-03-04 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhub_structure', '0002_topic_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMultipleChoiceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('multiple_choice_exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to='testhub_structure.multiplechoicetest')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
