# Generated by Django 5.0.2 on 2024-03-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhub_structure', '0003_submissionmultiplechoicetest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmultiplechoicetest',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='multi_choice_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubmissionPyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_total_tests', models.PositiveIntegerField()),
                ('num_correct_tests', models.PositiveIntegerField()),
                ('incorrect_tests', models.TextField()),
                ('num_error_tests', models.PositiveIntegerField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('python_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='testhub_structure.pytest')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='py_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
