# Generated by Django 5.0.2 on 2024-03-09 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhub_structure', '0004_alter_submissionmultiplechoicetest_submitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmultiplechoicetest',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
