# Generated by Django 5.0.2 on 2024-03-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhub_structure', '0005_submissionmultiplechoicetest_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmultiplechoicetest',
            name='multiple_choice_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='testhub_structure.multiplechoicetest'),
        ),
    ]
