# Generated by Django 5.0.2 on 2024-03-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhub_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='Bulgarian', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
