# Generated by Django 5.0.2 on 2024-03-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhub_auth', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user_images/defaultProfilePic.png', upload_to='user_images/'),
        ),
    ]
